import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Link href={'/'}>
          <button className='btn btn-outline btn-accent'>Home</button>
        </Link>
        <Link href={'/users'}>
          <button className='btn btn-outline btn-secondary'>Users</button>
        </Link>

        <Link href={'/users/new'}>
          <button className='border border-black px-5 py-2 m-5 hover:bg-slate-100 duration-150 rounded-sm'>
            New User
          </button>
        </Link>

        <Link href={'/posts'}>
          <button className='btn btn-outline btn-secondary'>Posts</button>
        </Link>
        {children}
      </body>
    </html>
  )
}
